"""Expose Pydantic schemas."""

from .common import Attachment, KPIBlock, ListQuery, PaginatedResult
from .material import (
    Material,
    MaterialCreateRequest,
    MaterialDraft,
    MaterialsListResult,
    MaterialReference,
    MaterialResponse,
    MaterialUpdateRequest,
    MaterialsListItem,
    MaterialsListQuery,
)
from .model import (
    CuttingPartUsage,
    HardwareItemOption,
    HardwareSet,
    InsoleOption,
    Model,
    ModelCreateRequest,
    ModelDraft,
    ModelListItem,
    ModelResponse,
    ModelSuperBOM,
    ModelUpdateRequest,
    ModelVariant,
    ModelVariantSpecification,
    ModelsListQuery,
    ModelsListResult,
    PerforationOption,
    SoleOption,
)
from .reference import ReferenceDraft, ReferenceItem, ReferenceListQuery, ReferenceListResult
from .warehouse import (
    WarehouseInventoryDraft,
    WarehouseInventoryLine,
    WarehouseIssueDraft,
    WarehouseIssueLine,
    WarehouseListQuery,
    WarehouseListResult,
    WarehouseReceiptDraft,
    WarehouseReceiptLine,
    WarehouseStock,
    WarehouseStockListItem,
)

__all__ = [
    "Attachment",
    "KPIBlock",
    "ListQuery",
    "PaginatedResult",
    "Material",
    "MaterialCreateRequest",
    "MaterialDraft",
    "MaterialsListResult",
    "MaterialReference",
    "MaterialResponse",
    "MaterialUpdateRequest",
    "MaterialsListItem",
    "MaterialsListQuery",
    "CuttingPartUsage",
    "HardwareItemOption",
    "HardwareSet",
    "InsoleOption",
    "Model",
    "ModelCreateRequest",
    "ModelDraft",
    "ModelListItem",
    "ModelResponse",
    "ModelSuperBOM",
    "ModelUpdateRequest",
    "ModelVariant",
    "ModelVariantSpecification",
    "ModelsListQuery",
    "ModelsListResult",
    "PerforationOption",
    "SoleOption",
    "ReferenceDraft",
    "ReferenceItem",
    "ReferenceListQuery",
    "ReferenceListResult",
    "WarehouseInventoryDraft",
    "WarehouseInventoryLine",
    "WarehouseIssueDraft",
    "WarehouseIssueLine",
    "WarehouseListQuery",
    "WarehouseListResult",
    "WarehouseReceiptDraft",
    "WarehouseReceiptLine",
    "WarehouseStock",
    "WarehouseStockListItem",
]
